
spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/userdb
    username: user
    password: password
    hikari:
      maximum-pool-size: 15
      connection-timeout: 30000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: user-service

#eureka.client.service-url.defaultZone=https://hemo-discovery-app.azurewebsites.net/eureka
