spring:
  application:
    name: user-service
  profiles:
    active: dev  # Default profile
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_DB_HOST}
      port: ${REDIS_DB_PORT}
      password: ${REDIS_DB_PASSWORD}

  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9020
  servlet:
    context-path: /users

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secretKey: ${JWT_SECRET_KEY}

