spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}


