
spring:
  datasource:
    url: jdbc:postgresql://matching-db:5432/matchingdb
    username: user
    password: password
    hikari:
      maximum-pool-size: 15
      connection-timeout: 30000

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/eureka
  instance:
    prefer-ip-address: true
    hostname: matching-service
    lease-renewal-interval-in-seconds: 10  # Faster detection
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      zone: primary  # Useful for Azure availability zones