# application.yml - Shared across all profiles
spring:
  application:
    name: matching-service
  profiles:
    active: dev  # Default profile
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_DB_HOST}
      port: ${REDIS_DB_PORT}
      password: ${REDIS_DB_PASSWORD}
  security:
    user:
      password: ${MATCHING_USER_PASSWORD}
server:
  servlet:
    context-path: /matching
  port: 9010

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info



# JWT Configuration
jwt:
  secretKey: ${JWT_SECRET_KEY}