spring:
  application:
    name: discovery-server



eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

# Host on 0.0.0.0 and a known port (like 8761)
server:
  port: 8761
  address: 0.0.0.0


