spring:
  application:
    name:
      api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  profiles:
    active: dev

server:
  port: 8080



jwt.secretKey: ${JWT_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info


user.endpoint: ${USER_SERVICE_URL}
matching.endpoint: ${MATCHING_SERVICE_URL}