spring:
  application:
    name:
      api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: default-route
          uri: no://op
          predicates:
              - Path=/
          filters:
            - SetStatus=200
            - SetResponseHeader=Content-Type,text/plain
            - SetResponseBody=API Gateway is running
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
        - id: matching-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/matching/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

server:
  port: 8080
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

jwt.secretKey: ${JWT_SECRET_KEY}
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
