spring:
  application:
    name:
      api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
        - id: matching-service
          uri: lb://MATCHING-SERVICE
          predicates:
            - Path=/api/v1/matching/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
      default-filters:
        - RemoveRequestHeader=Cookie
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt.secretKey: dshf091283h4sjkfh0932844hkvbxczkue45908hv2o489vhb9a83hrdkvyv90482hf0893
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
