spring:
  application:
    name:
      api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
        - id: matching-service
          uri: lb://MATCHING-SERVICE
          predicates:
            - Path=/api/v1/matching/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: https://${WEBSITE_HOSTNAME}:8761/eureka/eureka
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false
    hostname: ${WEBSITE_HOSTNAME}

server:
  port: 8080
  forward-headers-strategy: framework

jwt.secretKey: ${JWT_SECRET_KEY}
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
